### PR TITLE
Fix add layer and save not showing up

### LINKED ISSUE #148: Fix Save button not showing up in save map
the sources in the config do not include the `access_token`

### PR DESCRIPTION
**Pull request by milafrerichs**
## What does this PR do?
due to a wrong default geonode config the access_token is not available the save does not depend on the local geoserver the layerlist should not depend on it, since you can specify a server yourself
add defaults for both and add more tests
## Related Issue
fixes #148

### CODE REVIEW

File: src/components/geonode.jsx [hunk 1]
```diff
@@ -106,6 +106,21 @@ class GeoNodeViewer extends React.Component {
...
+  _createLayerList() {
+    let layerList;
+    if(this._local) {
+      layerList = {
+        sources: [{title: this._local.title, url: this._local.url, type: 'WMS'}],
+        allowUserInput: true
+      };
+    } else {
+      layerList = {
+        sources: [{title: 'Local Geoserver', url: this.props.server+'/geoserver/wms', type: 'WMS'}],
```
Comment (bartvde) [inline src/components/geonode.jsx:118]: is there always a proxy available? My default geonode setup gives a 404 on http://localhost:8000/geoserver

Should this be 8080 instead as the default?

**Review by bartvde — APPROVED** [review]

File: src/components/geonode.jsx (hunk 1 above)
Comment (milafrerichs) [reply src/components/geonode.jsx:118]: yes, maybe we change that to add a geoserver url... not sure, need to think about it
